/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiyun_engine_skeleton_Skeleton */

#ifndef _Included_com_wiyun_engine_skeleton_Skeleton
#define _Included_com_wiyun_engine_skeleton_Skeleton
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiyun_engine_skeleton_Skeleton
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_nativeStart
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_addGold
  (JNIEnv *, jobject, jint goldnum);
  
JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_addGem
  (JNIEnv *, jobject, jint gemnum);
  
JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_purchaseItem
  (JNIEnv *, jobject, jint itemId);
  
JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_replayBGM
  (JNIEnv *, jobject, jint itemId);
    
JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_onResumeGame
    (JNIEnv *, jobject);
    
    JNIEXPORT int JNICALL Java_com_wiyun_engine_skeleton_Skeleton_isShopOpening
    (JNIEnv *, jobject);
    
    JNIEXPORT void JNICALL Java_com_wiyun_engine_skeleton_Skeleton_setShopNeedReloadTex
    (JNIEnv *, jobject);

//    JNIEXPORT int JNICALL Java_com_wiyun_engine_skeleton_Skeleton_checkPackageNameJNI
//    (JNIEnv * env, jobject thiz);
  
void startPurchaseGameItem(int itemId);

void showAd(int type);
void hideAd();
void showExit();
void showOfferWall(int type = 0);
void reportEvent(const char* event_id, const char* label);
void showWebUrl(const char *url);
void showChartBoost();
void callGC();
    void showLeaderBoard();
    void submitScore(int score);
    void submitScoreAndShowLB(int score);
    void onResumeGameEnd();
    void showUIProgress();
    void hideUIProgress();

    int checkGamePackageName();
    int checkSignature();
    
    void showRateMeGoogle();
    
    void playVungleVedio();
    
void reportGaEvent(const char* category, const char* action, const char *label, int value);

#define FEELINGTOUCH 1

#ifdef __cplusplus
}
#endif
#endif
